CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS lessons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    lesson_id INT ,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS user_lessons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    lesson_id INT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE SET NULL
);




CREATE TABLE IF NOT EXISTS answer_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_id INT NOT NULL,
    user_id INT NOT NULL,
    answer TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

INSERT INTO lessons (name) VALUES
('Lessons 1'),
('Lessons 2'),
('Lessons 3'),
('Lessons 4'),
('Lessons 5'),
('Lessons 6'),
('Lessons 7'),
('Lessons 8'),
('Lessons 9'),
('Lessons 10'),
('Lessons 11'),
('Lessons 12'),
('Lessons 13'),
('Lessons 14'),
('Lessons 15'),
('Lessons 16'),
('Lessons 17'),
('Lessons 18'),
('Lessons 19'),
('Lessons 20'),
('Lessons 21'),
('Lessons 22'),
('Lessons 23'),
('Lessons 24'),
('Lessons 25'),
('Lessons 26'),
('Lessons 27'),
('Lessons 28'),
('Lessons 29'),
('Lessons 30'),
('Lessons 31'),
('Lessons 32'),
('Lessons 33'),
('Lessons 34'),
('Lessons 35'),
('Lessons 36'),
('Lessons 37'),
('Lessons 38'),
('Lessons 39'),
('Lessons 40'),
('Lessons 41'),
('Lessons 42'),
('Lessons 43'),
('Lessons 44'),
('Lessons 45'),
('Lessons 46'),
('Lessons 47'),
('Lessons 48'),
('Lessons 49'),
('Lessons 50'),
('Lessons 51'),
('Lessons 52'),
('Lessons 53'),
('Lessons 54'),
('Lessons 55'),
('Lessons 56'),
('Lessons 57'),
('Lessons 58'),
('Lessons 59'),
('Lessons 60'),
('Lessons 61'),
('Lessons 62'),
('Lessons 63'),
('Lessons 64'),
('Lessons 65'),
('Lessons 66'),
('Lessons 67'),
('Lessons 68'),
('Lessons 69'),
('Lessons 70'),
('Lessons 71'),
('Lessons 72'),
('Lessons 73'),
('Lessons 74'),
('Lessons 75'),
('Lessons 76'),
('Lessons 77'),
('Lessons 78'),
('Lessons 79'),
('Lessons 80'),
('Lessons 81'),
('Lessons 82'),
('Lessons 83'),
('Lessons 84'),
('Lessons 85'),
('Lessons 86'),
('Lessons 87'),
('Lessons 88'),
('Lessons 89'),
('Lessons 90'),
('Lessons 91'),
('Lessons 92'),
('Lessons 93'),
('Lessons 94'),
('Lessons 95'),
('Lessons 96'),
('Lessons 97'),
('Lessons 98'),
('Lessons 99'),
('Lessons 100'),
('Lessons 101'),
('Lessons 102'),
('Lessons 103'),
('Lessons 104'),
('Lessons 105'),
('Lessons 106'),
('Lessons 107'),
('Lessons 108'),
('Lessons 109'),
('Lessons 110'),
('Lessons 111'),
('Lessons 112'),
('Lessons 113'),
('Lessons 114'),
('Lessons 115'),
('Lessons 116'),
('Lessons 117'),
('Lessons 118'),
('Lessons 119'),
('Lessons 120'),
('Lessons 121'),
('Lessons 122'),
('Lessons 123'),
('Lessons 124'),
('Lessons 125'),
('Lessons 126'),
('Lessons 127'),
('Lessons 128'),
('Lessons 129'),
('Lessons 130'),
('Lessons 131'),  
('Lessons 132'),  
('Lessons 133'),  
('Lessons 134'),  
('Lessons 135'),  
('Lessons 136'),  
('Lessons 137'),  
('Lessons 138'),  
('Lessons 139'),  
('Lessons 140'),  
('Lessons 141'),  
('Lessons 142'),  
('Lessons 143'),  
('Lessons 144'),  
('Lessons 145'),  
('Lessons 146'),  
('Lessons 147'),  
('Lessons 148'),  
('Lessons 149'),  
('Lessons 150'),  
('Lessons 151'),  
('Lessons 152'),  
('Lessons 153'),  
('Lessons 154'),  
('Lessons 155'),  
('Lessons 156'),  
('Lessons 157'),  
('Lessons 158'),  
('Lessons 159'),  
('Lessons 160'),  
('Lessons 161'),  
('Lessons 162'),  
('Lessons 163'),  
('Lessons 164'),  
('Lessons 165'),  
('Lessons 166'),  
('Lessons 167'),  
('Lessons 168'),  
('Lessons 169'),  
('Lessons 170'),  
('Lessons 171'),  
('Lessons 172'),  
('Lessons 173'),  
('Lessons 174'),  
('Lessons 175'),  
('Lessons 176'),  
('Lessons 177'),  
('Lessons 178'),  
('Lessons 179'),  
('Lessons 180'),  
('Lessons 181'),  
('Lessons 182'),  
('Lessons 183'),  
('Lessons 184'),  
('Lessons 185'),  
('Lessons 186'),  
('Lessons 187'),  
('Lessons 188'),  
('Lessons 189'),  
('Lessons 190'),  
('Lessons 191'),  
('Lessons 192'),  
('Lessons 193'),  
('Lessons 194'),  
('Lessons 195'),  
('Lessons 196'),  
('Lessons 197'),  
('Lessons 198'),  
('Lessons 199'),  
('Lessons 200'),  
('Lessons 201'),  
('Lessons 202'),  
('Lessons 203'),  
('Lessons 204'),  
('Lessons 205'),  
('Lessons 206'),  
('Lessons 207'),  
('Lessons 208'),  
('Lessons 209'),  
('Lessons 210'),  
('Lessons 211'),  
('Lessons 212'),  
('Lessons 213'),  
('Lessons 214'),  
('Lessons 215'),  
('Lessons 216'),  
('Lessons 217'),  
('Lessons 218'),  
('Lessons 219'),  
('Lessons 220'),  
('Lessons 221'),  
('Lessons 222'),  
('Lessons 223'),  
('Lessons 224'),  
('Lessons 225'),  
('Lessons 226'),  
('Lessons 227'),  
('Lessons 228'),  
('Lessons 229'),  
('Lessons 230'),  
('Lessons 231'),  
('Lessons 232'),  
('Lessons 233'),  
('Lessons 234'),  
('Lessons 235'),  
('Lessons 236'),  
('Lessons 237'),  
('Lessons 238'),  
('Lessons 239'),  
('Lessons 240'),  
('Lessons 241'),  
('Lessons 242'),  
('Lessons 243'),  
('Lessons 244'),   
('Lessons 245'),
('Lessons 246'),
('Lessons 247'),
('Lessons 248'),
('Lessons 249'),
('Lessons 250'),
('Lessons 251'),
('Lessons 252'),
('Lessons 253'),
('Lessons 254'),
('Lessons 255'),
('Lessons 256'),
('Lessons 257'),
('Lessons 258'),
('Lessons 259'),
('Lessons 260'),
('Lessons 261'),
('Lessons 262'),
('Lessons 263'),
('Lessons 264'),
('Lessons 265'),
('Lessons 266'),
('Lessons 267'),
('Lessons 268'),
('Lessons 269'),
('Lessons 270'),
('Lessons 271'),
('Lessons 272'),
('Lessons 273'),
('Lessons 274'),
('Lessons 275'),
('Lessons 276'),
('Lessons 277'),
('Lessons 278'),
('Lessons 279'),
('Lessons 280'),
('Lessons 281'),
('Lessons 282'),
('Lessons 283'),
('Lessons 284'),
('Lessons 285'),
('Lessons 286'),
('Lessons 287'),
('Lessons 288'),
('Lessons 289'),
('Lessons 290'),
('Lessons 291'),
('Lessons 292'),
('Lessons 293'),
('Lessons 294'),
('Lessons 295'),
('Lessons 296'),
('Lessons 297'),
('Lessons 298'),
('Lessons 299'),
('Lessons 300');


INSERT INTO questions (text, lesson_id) VALUES
('I understand you', 1),
('They live in this country', 1),
('I travel every day', 1),
('I also think so', 1),
('I speak English', 1),
('I go to work', 1),
('I also think so', 1),
('I study and work', 1),
('I know it very well', 1),
('They live in this country', 1),
('They live in New York', 1),
('I understand it', 1),
('I undersand you', 1),
('I learn English', 1),
('I live in Russia', 1),
('I see it', 1),
('I understand you very well', 1),
('I speak English and Russia', 1),
('I also think so', 1),
('I like English', 1),
('I know', 1),
('I learn English online', 1),
('I know it', 1),
('I like this city', 1),
('I want it', 1),
('I work', 1),
('I see my results', 1),
('I stydy', 1),
('We understand you', 1),
('I work and study', 1),
('I like this programm', 1),
('You know', 1),
('I understand', 1),
('I like this video', 1),
('I see my result', 1),
('I also think so', 1),
('You help me', 1),
('I know it very well', 1),
('I also think so', 1),
('I like this place', 1),
('We live in this city', 1),
('You speak English very well', 1),
('I speak Russian', 1),
('I really want it', 1),
('I really understand this lesson', 1),
('I see it very well', 1),
('You really help me', 1),
('I sometimes think about it', 1),
('I think so', 1),
('They live there', 1),
('I think about it', 1),
('We usually buy it there', 1),
('I often think about it', 1),
('I like music', 1),
('I like these things', 1),
('I play this game', 1),
('I go there', 1),
('They also think so', 1),
('I often do it', 1),
('You work very well', 1),
('I do it every day', 1),
('I go to school', 1),
('I usually buy this thing there', 1),
('I buy that thing there', 1),
('I usually buy it here', 1),
('I read this book', 1),
('I read English books', 1),
('I read books', 1),
('We think so', 1),
('They think so', 1),
('We think about it', 1),
('We often go there', 1),
('I often go there', 1),
('I sometimes go there', 1),
('I also think so', 1),
('I also like it', 1),
('I also want it', 1),
('I travel every year', 1),
('I like this language', 1),
('I often travel', 1),
('I like that language', 1),
('We like this place', 1),
('I really like that place', 1),
('I like this thing', 1),
('I like these videos', 1),
('I go to work', 1),
('I go to this park', 1),
('I go to school', 1),
('I like english', 1),
('I like this practice', 1),
('I really like English', 1),
('I also think so', 1),
('They think so', 1),
('I often play this game', 1),
('I can help you', 1),
('I like this song', 1),
('They often play football', 1),
('I like travelling', 1),
('I often see these things', 1),
('I love this place', 1),
-- 2
('He sees this problem', 2),
('She understands it', 2),
('I like it very much', 2),
('She lives very far', 2),
('She likes this game', 2),
('It costs twenty euros', 2),
('She makes mistakes', 2),
('He often does it', 2),
('He usually buys these tickets', 2),
('I do it very often', 2),
('She lives there', 2),
('He agrees', 2),
('He often does it', 2),
('He lives very far', 2),
('It costs much less', 2),
('I agree with you', 2),
('He really wants it', 2),
('He often makes mistakes', 2),
('He sees this problem', 2),
('She knows it better', 2),
('He goes to work', 2),
('She understands it', 2),
('I really want it', 2),
('I absolutely agree with you', 2),
('She wants it', 2),
('He usually buys these tickets', 2),
('It costs less', 2),
('He feels better', 2),
('He sees this mistake', 2),
('She lives in that place', 2),
('It costs twenty euros', 2),
('He lives here', 2),
('he understands', 2),
('I live near', 2),
('She agrees with it', 2),
('He lives in that city', 2),
('She often buys these tickets', 2),
('She makes mistakes', 2),
('it costs much more', 2),
('It works very well', 2),
('It costs ten dollars', 2),
('She goes to school', 2),
('It costs fifty pounds', 2),
('I buy these tickets online', 2),
('He does it every day', 2),
('They work together', 2),
('I see this problem', 2),
('He knows English', 2),
('It costs more', 2),
('I know that it costs more', 2),
('i think he speaks English very well', 2),
('He often says it', 2),
('I know how it works', 2),
('I think it works very well', 2),
('He know a lot', 2),
('He understands that person', 2),
('I think he does it better', 2),
('We often hear it on TV', 2),
('He likes it', 2),
('I see that he feels much better', 2),
('I think that he understands us', 2),
('He often calls me', 2),
('He watches these videos', 2),
('He knows so little', 2),
('It helps me so much', 2),
('You help me so much', 2),
('It helps you so much', 2),
('I work so much', 2),
('She works so much', 2),
('You work too much', 2),
('It helps me', 2),
('They help me', 2),
('I sometimes say it', 2),
('He sometimes says it', 2),
('I hear you', 2),
('I hear them', 2),
('She hears me', 2),
('I think that you do it better', 2),
('I think that he does it better', 2),
('I know you do it better', 2),
('I understand these people', 2),
('I understand those people', 2),
('He understands those people', 2),
('He works so much', 2),
('He works so much', 2),
('She calls me sometimes', 2),
('She calls him sometimes', 2),
('They call me sometimes', 2),
('It really helps me', 2),
('You really help me', 2),
('It really helps him', 2),
('He likes this video', 2),
('He often tells me this thing', 2),
('I understand why it happens', 2),
('She always watches TV', 2),
('Sometimes he says it', 2),
('They often tell me these things', 2),
('She likes it', 2),
('I see it really helps me', 2),
('I think he works very well', 2),
-- 3
('I see a girl', 3),
('I want an apple', 3),
('I see one person', 3),
('They have money', 3),
('I like this car', 3),
('He likes these cars', 3),
('I have some questions', 3),
('She has some time', 3),
('I see a bus', 3),
('I have a book', 3),
('I have an idea', 3),
('I see an apple', 3),
('I have a brother', 3),
('I see a teacher', 3),
('I see a hotel', 3),
('I know this man', 3),
('I see a girl', 3),
('I have some results', 3),
('I want an apple', 3),
('I have an orange', 3),
('I understand your question', 3),
('I have a problem', 3),
('I see a woman', 3),
('i have time', 3),
('I see a university', 3),
('I have some questions', 3),
('I see a bus', 3),
('I like this car', 3),
('I have one problem', 3),
('We see a hotel', 3),
('I like this question', 3),
('I know this university', 3),
('They have money', 3),
('I see one person', 3),
('We see a bus', 3),
('They have a problem', 3),
('I like this university', 3),
('I want an orange', 3),
('I have a job', 3),
('I see a man', 3),
('I have a question', 3),
('I see a school', 3),
('We see a teacher', 3),
('I have a sister', 3),
('I see two people', 3),
('I have little free time', 3),
('I have an apple', 3),
('I see a house', 3),
('I have a car', 3),
('I know this person', 3),
('I see a boy', 3),
('I have some ideas', 3),
('I see two students', 3),
('I have a family', 3),
('We see a bank', 3),
('I see a student', 3),
('They often drink water', 3),
('They have a computer', 3),
('I understand these things', 3),
('I like this book', 3),
('I have a computer', 3),
('I really love music', 3),
('I eat fish', 3),
('I do different exercises', 3),
('We see a taxi', 3),
('I drink tea', 3),
('I like these exercises', 3),
('I have one book', 3),
('She has one book', 3),
('I have one computer', 3),
('I love sport', 3),
('He loves tea', 3),
('I like sport', 3),
('I see a bank', 3),
('She sees a bank', 3),
('I see this bank', 3),
('I understand these things', 3),
('I understand this thing', 3),
('We have two books', 3),
('They have motivation', 3),
('We have motivation', 3),
('She has motivation', 3),
('You have motivation', 3),
('We have a result', 3),
('I like my result', 3),
('I like this result', 3),
('I see my progress', 3),
('I see your progress', 3),
('He sees my progress', 3),
('I like my results', 3),
('She likes her results', 3),
('They like my results', 3),
('They often drink milk', 3),
('I see a taxi', 3),
('I love music', 3),
('They drink milk', 3),
('I often eat fish', 3),
('I want juice', 3),
-- 4
('We see two men', 4),
('I see a man and two women', 4),
('She has two children', 4),
('He has a question', 4),
('She has two daughters and a son', 4),
('I see you have a question', 4),
('I see that you have little free time', 4),
('She has two children', 4),
('I like English', 4),
('He sees one woman', 4),
('He has a question', 4),
('She has two daughters and a son', 4),
('She speaks English and German', 4),
('He has a child', 4),
('I really like English', 4),
('We see two men', 4),
('I see a mistake', 4),
('She has children', 4),
('He has a job', 4),
('I see a man and two women', 4),
('He has little free time', 4),
('I see three women', 4),
('He has a daughter', 4),
('They have a child', 4),
('He has an apartment', 4),
('They have two sons', 4),
('I see four people', 4),
('I like cakes', 4),
('She has little free time', 4),
('She sees a taxi', 4),
('She has a son', 4),
('We like seafood', 4),
('We see an airport', 4),
('He eats fish', 4),
('She has some questions', 4),
('I like chocolate', 4),
('I have an apartment', 4),
('They have a daughter', 4),
('She has a problem', 4),
('I like seafood', 4),
('I see an airport', 4),
('He has motivation', 4),
('He knows English and Spanish', 4),
('He sees an airport', 4),
('They eat meat and fish', 4),
('We see a woman and three men', 4),
('He eats meat', 4),
('He likes meat more', 4),
('It often happens', 4),
('I have an idea', 4),
('He has this money', 4),
('She likes swimming', 4),
('He works in a hospital', 4),
('He likes that hotel more', 4),
('She loves sport', 4),
('He knows English better', 4),
('We see a hospital', 4),
('She knows two foreign languages', 4),
('I see you have a question', 4),
('I like swimming', 4),
('She reads English books', 4),
('He has an idea', 4),
('I know one foreign language', 4),
('I know two foreign languages', 4),
('He knows many foreign languages', 4),
('I see that you have little free time', 4),
('I see she has little free time', 4),
('I see they have much free time', 4),
('He likes music', 4),
('She likes music', 4),
('They like music', 4),
('We see a university', 4),
('You see a building', 4),
('We see a school', 4),
('He likes swimming', 4),
('They like swimming', 4),
('I know he has a job', 4),
('I know that you have a job', 4),
('I know she has a job', 4),
('He likes these ideas', 4),
('He likes this idea', 4),
('I like these ideas', 4),
('I know he has money', 4),
('I know she has money', 4),
('We know he has some money', 4),
('He likes English', 4),
('She likes German', 4),
('We like English', 4),
('She likes fish more', 4),
('He likes fish more', 4),
('I like meat more', 4),
('I have this money', 4),
('He reads books in English', 4),
('She likes that place more', 4),
('I love sport so much', 4),
('She has a boyfriend', 4),
('I learn foreign languages', 4),
('I see her boyfriend', 4),
('We have an idea', 4),
('I see a hospital', 4),
-- 5
('I want to see it', 5),
("I'd like to go there now", 5),
("I'd like to speak English better", 5),
('I want to see her', 5),
('I want to see them', 5),
('I want to see him', 5),
('He wants to help me', 5),
('She wants to help us', 5),
('I want to do it this week', 5),
('I want to go to China next year', 5),
('I want to see her', 5),
('I want to speak English', 5),
('I want to be a doctor', 5),
('I want to speak English fluently and correctly', 5),
('I want to visit this country', 5),
('He wants to be a teacher', 5),
('I want to speak English without mistakes', 5),
('I want to become a programmer', 5),
('I want to see them', 5),
('I want to be happy', 5),
('He wants to become a businessman', 5),
("I'd like to speak English fluently and correctly", 5),
('I want ot speak English', 5),
('I want to see him', 5),
("I'd like to go there now", 5),
('I want ot be a businessman', 5),
('I want to visit this city', 5),
('She wants to be a teacher', 5),
('I want to do it now', 5),
('I want to buy it', 5),
('I want to call him', 5),
('I want to be a designer', 5),
('I want to visit new', 5),
('I want to call her now', 5),
("I'd like to speak English better", 5),
('I want to work', 5),
('I want to be a manager', 5),
('I want to travel', 5),
('I want to be a teacher', 5),
('I want it', 5),
('I want to become a teacher', 5),
('She wants to live abroad', 5),
('I really want to understand it', 5),
('We want to buy that thing', 5),
("I'd like to speak English fluently", 5),
('I want to be a programmer', 5),
('I want to understand it', 5),
('I want to speak English fluently', 5),
("I'd like to speak English correctly", 5),
('I want to buy this thing', 5),
('I understand her', 5),
('He wants to help me', 5),
('He wants to study there', 5),
('I want to live in this city', 5),
('She wants to help us', 5),
("I'd like to read English books", 5),
('I want to live in this country', 5),
('I want to buy two tickets', 5),
('I see his father', 5),
('I want to buy a computer', 5),
('I like their idea', 5),
("I'd like to speak English without mistakes", 5),
("I'd like to visit new countries and cities", 5),
('I see her mother', 5),
("I'd like to go to England", 5),
('They want to study abroad', 5),
('He wants to study abroad', 5),
('I want to study in my country', 5),
('I want to read these books', 5),
('I want to read this book', 5),
('He wants to read those books', 5),
('I want to do it this week', 5),
('She wants to do it this week', 5),
('I want to do it tomorrow', 5),
('I understand him', 5),
('She understands him', 5),
('He understands me', 5),
('He wants to live abroad', 5),
('I want to live abroad', 5),
('They want to live abroad', 5),
('I know him', 5),
('You know me', 5),
('He knows her', 5),
('I want to help you', 5),
('They want to help me', 5),
('We know her', 5),
('They know him', 5),
('I know you very well', 5),
('I want to visit England this year', 5),
('He wants to visit Russia this year', 5),
('I want to visit Germany next month', 5),
('I want to go to China next year', 5),
('He wants to go to England next year', 5),
('He wants to go to China this year', 5),
('We want to visit Italy next month', 5),
('I want to learn English here', 5),
('I want to read that book', 5),
('I see their house', 5),
("I'd like to visit Japan", 5),
("I'd like to go to the United States", 5),
-- 6
("It doesn't interest them", 6),
("He doesn't have any question", 6),
("I don't have any plans", 6),
("He doesn't feel happy", 6),
('I use the Internet every day', 6),
('I use this service', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),
('', 6),

-- 7
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
('', 7),
-- 8
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),
('', 8),

-- 9
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),
('', 9),

-- 10
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10),
('', 10);